[package]
name = "swarmy"
version = "0.1.0"
description = "Swarmy Tauri App"
authors = ["Seb Ospina <kraige@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "swarmy_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
nom-mpq = "2.0.7"
s2protocol = { workspace = true }
swarmy-common = { path = "../swarmy-common" }
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-log = "2"
tauri-plugin-fs = "2.5.1"
tauri-plugin-persisted-scope = "2"
tauri-plugin-store = "2"
tauri-plugin-shell = "2"
tauri-plugin-clipboard-manager = "2"
log = "0.4"
chrono = { version = "0.4.41", features = [] }
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
colored = "3.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
mimalloc = "0.1.52"
rerun = { version = "0.25", features = [
  "native_viewer",
] } # Need 0.25 because of chrono 0.4.41 required by polars-arrow

[dev-dependencies]
test-log = { version = "0.2", default-features = false, features = ["trace"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
polars = { version = "0.53.0", default-features = false }
reqwest = "0.13"
tokio = { version = "1", features = ["full"] }
tracing = { workspace = true }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2"
