[package]
name = "swarmy-ui"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Starcraft II - Replay collection analyser and visualizer"
repository = "https://github.com/sebosp/swarmy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
leptos = { version = "0.8", features = ["csr"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.6"
console_error_panic_hook = "0.1.7"
reactive_stores = "0.4"
reactive_graph = "0.2"
phosphor-leptos = "0.8.0"
swarmy-common = { path = "swarmy-common" }
s2protocol = { workspace = true }
tracing = { workspace = true }
si-scale = "0.3"
chrono = { version = "0.4.41", features = ["serde"] }

[workspace]
members = ["src-tauri", "swarmy-common"]

[workspace.dependencies]
s2protocol = { path = "../s2protocol-rs/", default-features = false, features = [
    "dep_arrow",
] }
tracing = "0.1.44"

[profile.dev]
incremental = true
opt-level = 0
debug = true

[profile.dev.package."*"]
opt-level = 1
debug = false
